[server]
headless = true
port = 5179
address = "localhost"
maxUploadSize = 50

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 5179

[theme]
base = "dark"
primaryColor = "#7c5cfc"
backgroundColor = "#0b0b0e"
secondaryBackgroundColor = "#141418"
textColor = "#ececf1"
font = "sans serif"
